{{- if .Values.isManagement }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Chart.Name }}-namespace
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
  serviceSpec:
    services:
      - name: {{ .Chart.Name }}-namespace
        namespace: {{ .Values.kcm.namespace }}
        template: {{ .Chart.Name }}-namespace
        values: |
          features:
            namespace:
              enabled: true
          clusterName: {{ `{{ .Cluster.metadata.name }}` }}
{{- end }}
