{{- if .Values.isManagement }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Chart.Name }}-namespace
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
  serviceSpec:
    services:
      - name: {{ .Chart.Name }}-namespace
        namespace: {{ .Values.kcm.namespace }}
        template: {{ .Chart.Name }}-propagation
        values: |
          propagation:
            enabled: true
            data: |
              apiVersion: v1
              kind: Namespace
              metadata:
                name: istio-system
                annotations:
                  helm.sh/resource-policy: keep
                labels:
                  topology.istio.io/network: {{ printf "%s-network" `{{ .Cluster.metadata.name }}` | quote }}
{{- end }}
