{{- if .Values.isManagement }}
{{- $chartVersion := .Chart.Version | replace "." "-" }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Chart.Name }}-namespace
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-role: member
  serviceSpec:
    services:
      - name: {{ .Chart.Name }}-namespace-cm
        namespace: {{ .Values.kcm.namespace }}
        template: {{ .Chart.Name }}-propagation-{{ $chartVersion }}
        values: |
          {{`{{- $eligible := and .Cluster.metadata.labels (eq (index .Cluster.metadata.labels "k0rdent.mirantis.com/kcm-region-cluster") "true") }}`}}
          propagation:
            enabled: {{`{{ $eligible }}`}}
            data: |
              {{`{{ if $eligible }}`}}
              {{`{{ removeField "ConfigMap" "metadata.ownerReferences" | nindent 14 }}`}}
              {{`{{ end }}`}}
      - name: {{ .Chart.Name }}-namespace
        namespace: {{ .Values.kcm.namespace }}
        template: {{ .Chart.Name }}-namespace-{{ $chartVersion }}
        dependsOn:
          - name: {{ .Chart.Name }}-namespace-cm
            namespace: {{ .Values.kcm.namespace }}
    templateResourceRefs:
      - identifier: ConfigMap
        resource:
          apiVersion: v1
          kind: ConfigMap
          name: {{ .Chart.Name }}-namespace-template
          namespace: {{ .Values.kcm.namespace }}
{{- end }}
