{{- if .Values.isManagement }}
{{- $version := .Values.gateway.version | replace "." "-" }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: MultiClusterService
metadata:
  name: {{ .Chart.Name }}-gateway
spec:
  clusterSelector:
    matchLabels:
      k0rdent.mirantis.com/istio-gateway: "true"
  dependsOn:
    - {{ .Chart.Name }}-network
  serviceSpec:
    services:
      - name: istio-gateway
        namespace: {{ .Release.Namespace }}
        template: {{ .Chart.Name }}-gateway-{{ $version }}
        values: |
          networkGateway: {{ `{{ .Cluster.metadata.name }}` }}-network
          labels:
            istio: eastwestgateway

      {{- if .Values.gateway.resource }}
      - name: gateway-template
        namespace: {{ .Release.Namespace }}
        template: {{ .Chart.Name }}-gateway-template
        dependsOn:
          - name: istio-gateway
            namespace: {{ .Release.Namespace }}
        values: |
          features:
            gateway:
              enabled: true
          clusterName: {{ `{{ .Cluster.metadata.name }}` }}
          gateway:
            resource:
{{ toYaml .Values.gateway.resource | indent 14 }}
      {{- end }}
{{- end }}
