{{- if .Values.isManagement }}
{{- $version := .Values.gateway.version | replace "." "-" }}
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ServiceTemplate
metadata:
  name: {{ .Chart.Name }}-gateway-{{ $version }}
  namespace: {{ .Values.kcm.namespace }}
spec:
  helm:
    chartSpec:
      chart: gateway
      version: {{ .Values.gateway.version }}
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: {{ .Values.istio.repo.name }}
{{- end }}
