{{- if .Values.features.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    topology.istio.io/network: {{ printf "%s-network" .Values.clusterName | quote }}
{{- end }}
