{{ range $name, $value := .Values.intermediateCAs }}
{{- if $value.certificate }}
{{- $hash := printf "%s-%s" $value.namespace $name | adler32sum }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca-certificate-{{ $hash }}
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: {{ $name }} CA
  subject:
    organizations:
      - Istio
  secretName: istio-ca-secret-{{ $hash }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $.Chart.Name }}-root
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- if $value.issuer }}
{{- $hash := printf "%s-%s" $value.namespace $name | adler32sum }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca-issuer-{{ $hash }}
  namespace: {{ $.Release.Namespace }}
spec:
  ca:
    secretName: istio-ca-secret-{{ $hash }}
{{- end }}
{{- end }}
