{{- $csrIssuerName := index $.Values "cert-manager-istio-csr" "app" "certmanager" "issuer" "name" }}
{{- $suffix := replace "istio-ca-issuer-" "" $csrIssuerName }}
{{- $clusterID := index $.Values "cert-manager-istio-csr" "app" "server" "clusterID" }}
{{- if .Values.intermediateCA.certificate }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ca-certificate-{{ $suffix }}
  namespace: {{ $.Release.Namespace }}
spec:
  isCA: true
  commonName: {{ $clusterID }} CA
  subject:
    organizations:
      - Istio
  secretName: istio-ca-secret-{{ $suffix }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ $.Chart.Name }}-root
    kind: Issuer
    group: cert-manager.io
{{- end }}
{{- if .Values.intermediateCA.issuer }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: istio-ca-issuer-{{ $suffix }}
  namespace: {{ $.Release.Namespace }}
spec:
  ca:
    secretName: istio-ca-secret-{{ $suffix }}
{{- end }}
