name: "Chart Smoke Tests"

on:
  pull_request:
    paths:
      - "charts/**"
      - "scripts/chart_smoke_tests.sh"
      - ".github/workflows/chart_tests.yml"
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install YQ
        uses: mikefarah/yq@v4

      - name: Run chart smoke tests
        run: bash scripts/chart_smoke_tests.sh
